name: dart_consumer
description: A kafka consumer
version: 1.0.0
author: Markus Krebs <markuskrebs93@gmail.com>
homepage: https://www.jayjah.eu

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

environment:
  sdk: ">=2.6.0 <2.12.0"

# dependencies
dependencies:
  kafka:
    git:
      url: https://github.com/dart-kafka/kafka.git
      ref: kafka-0.10